version: "2"
services:
  web:
    build: .
    restart: always
    volumes:
      - .:/var/app
      - ~/.bash_history:/root/.bash_history
      - ./config/database.yml:/var/config/database.yml
    ports:
      - "3000:3000"
    environment:
      - "RAILS_ENV=development"
    depends_on:
      - postgres
    tty: true
    stdin_open: true

  postgres:
    image: postgres:12.1-alpine
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD="
      - "POSTGRES_DB=agendamento_covid_development"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
